services:
  mysql:
    image: mysql:8.0.44
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: chatsystem
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3000:3306"
    volumes:
      - ./data/mysql:/var/lib/mysql

  redis:
    image: redis:7.4.9
    ports:
      - "16000:6379"
    volumes:
      - ./data/redis/data:/data

  redis-insight:
    image: redis/redisinsight:2.70.1
    ports:
      - "15000:5540"
    volumes:
      - ./data/redis-insight:/data
